# Generated by Django 2.1.2 on 2018-10-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=100)),
                ('what', models.CharField(max_length=600)),
                ('where', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
