# Generated by Django 2.1.2 on 2018-10-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Event date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='what',
            field=models.TextField(max_length=600),
        ),
    ]
