# Generated by Django 2.1.2 on 2018-10-15 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
